In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [7]:
df=pd.read_csv('cars.csv')

In [8]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df['fuel'].value_counts()
from category_encoders import BinaryEncoder

encoder = BinaryEncoder(cols=['column'])
data = encoder.fit_transform(data)

ImportError: cannot import name 'BinaryEncoder' from '_compat_pickle' (c:\Users\nic\anaconda3\Lib\_compat_pickle.py)

In [ ]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [ ]:
### One-Hot encoding using pandas
### Converting Categorical data into numerical and removing the first column of every categorical column
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [ ]:
### onehotencoding using sckit learn
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [ ]:
X_train_new

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 9)>

In [ ]:
X_test_new=ohe.fit_transform(X_test[['fuel','owner']])
X_test_new

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3252 stored elements and shape (1626, 9)>

In [ ]:

X_train_new1=X_train_new.toarray()
X_train_new1

lr=LinearRegression()
lr.fit(X_train_new1,y_train)
y_pred=lr.predict(X_test_new)

In [ ]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new1)).shape

(6502, 11)

In [ ]:
counts=df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df['brand'].nunique()
threshold=100

In [ ]:
repl=counts[counts<=threshold].index
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [ ]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'))

##here all the brand which has less than 100 is group in uncommon feature and those who are more than or equal to 100 are been make a feature

        BMW  Chevrolet   Ford  Honda  ...   Tata  Toyota  Volkswagen  uncommon
0     False      False  False  False  ...  False   False       False     False
1     False      False  False  False  ...  False   False       False     False
2     False      False  False   True  ...  False   False       False     False
3     False      False  False  False  ...  False   False       False     False
4     False      False  False  False  ...  False   False       False     False
...     ...        ...    ...    ...  ...    ...     ...         ...       ...
8123  False      False  False  False  ...  False   False       False     False
8124  False      False  False  False  ...  False   False       False     False
8125  False      False  False  False  ...  False   False       False     False
8126  False      False  False  False  ...   True   False       False     False
8127  False      False  False  False  ...   True   False       False     False

[8128 rows x 13 columns]